version: '3'

services:
  db:
    image: mysql/mysql-server:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD:  "123456"
      MYSQL_DATABASE: "Pomelo"
      MYSQL_USER: "pomelo"
      MYSQL_PASSWORD: "123456"
      MYSQL_LOG_CONSOLE: "true"
    restart: always
  
  app:
    build: .
    links:
      - db
    ports:
      - 3000:8080
    volumes:
      - .:/usr/src/app