version: '3'

services:
  db:
    image: mysql/mysql-server:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/db:/data/work/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "localhost"
      MYSQL_ROOT_PASSWORD:  "123456"
      MYSQL_DATABASE: "Pomelo"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_LOG_CONSOLE: "true"
    restart: always
  
  app:
    build: .
    command: npm start
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules